import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react'

import { ReduxProvider } from "@/utils/reduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chit-Chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ReduxProvider>
      <ChakraProvider>{children}</ChakraProvider>
      </ReduxProvider>
        </body>
    </html>
  );
}
